/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Tue Oct 28 06:21:30 ICT 2014
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.erv.model;

public class GirokeluarKey implements java.io.Serializable, Cloneable {
    /* ID */
    protected int id;

    /* ID */
    public int getId() {
        return id;
    }

    /* ID */
    public void setId(int id) {
        this.id = id;
    }

    /* Calculate hash code */
    public int hashCode() {
        int hashCode = 0;
        hashCode += new Integer(id).hashCode();
        return hashCode;
    }
    
    /* Indicates whether some other object is "equal to" this one. */
    public boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null || !(obj instanceof GirokeluarKey))
            return false;

        GirokeluarKey key = (GirokeluarKey) obj;

        if (this.id != key.id)
            return false;

        return true;
    }

    /* Creates and returns a copy of this object. */
    public Object clone()
    {
        GirokeluarKey key = new GirokeluarKey();
        key.id = this.id;
        return key;
    }

    /* Returns a string representation of the object. */
    public String toString() {
        String sep = "\r\n";
        StringBuffer sb = new StringBuffer();
        sb.append(this.getClass().getName()).append(sep);
        sb.append("[").append("id").append(" = ").append(id).append("]");
        return sb.toString();
    }
}