/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Tue Oct 28 06:21:30 ICT 2014
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.erv.model;

import java.util.Date;

/*
 * For Table GIROKELUAR
 */
public class Girokeluar  {
    protected int id;
    protected String nomorgiro;
    protected Date tglgiro;
    protected Date tgljtempo;
    protected double jumlah;
    protected String namapenerima;
    protected int status;
    protected String kodesupplier;
    protected String idbank;
    protected String banktujuan;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getNomorgiro() {
        return nomorgiro;
    }

    public void setNomorgiro(String nomorgiro) {
        this.nomorgiro = nomorgiro;
    }

    public Date getTglgiro() {
        return tglgiro;
    }

    public void setTglgiro(Date tglgiro) {
        this.tglgiro = tglgiro;
    }

    public Date getTgljtempo() {
        return tgljtempo;
    }

    public void setTgljtempo(Date tgljtempo) {
        this.tgljtempo = tgljtempo;
    }
    
    public double getJumlah() {
        return jumlah;
    }

    public void setJumlah(double jumlah) {
        this.jumlah = jumlah;
    }

    public String getNamapenerima() {
        return namapenerima;
    }

    public void setNamapenerima(String namapenerima) {
        this.namapenerima = namapenerima;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public String getKodesupplier() {
        return kodesupplier;
    }

    public void setKodesupplier(String kodesupplier) {
        this.kodesupplier = kodesupplier;
    }

    public String getIdbank() {
        return idbank;
    }

    public void setIdbank(String idbank) {
        this.idbank = idbank;
    }

    public String getBanktujuan() {
        return banktujuan;
    }

    public void setBanktujuan(String banktujuan) {
        this.banktujuan = banktujuan;
    }
}