/*
 * This java source file is generated by DAO4J v1.19
 * Generated on Tue Oct 28 06:21:30 ICT 2014
 * For more information, please contact b-i-d@163.com
 * Please check http://sourceforge.net/projects/dao4j/ for the latest version.
 */

package com.erv.model.dao;

import com.erv.exception.JavarieException;
import com.erv.model.*;
import java.util.List;

/**
 * This interface provides methods to populate DB Table of GIROKELUAR
 */
public interface GirokeluarDAO {
    public void create(Girokeluar bean) throws JavarieException;
    public Girokeluar load(GirokeluarKey key) throws JavarieException;
    public void update(Girokeluar bean) throws JavarieException;
    public void delete(GirokeluarKey key) throws JavarieException;
    public String getKodeGiroKeluar() throws JavarieException;
    public List<Girokeluar> selectAll(String kriteria,int limit) throws JavarieException;
    public void angsuranHutang(Girokeluar girokeluar, String tgl) throws JavarieException;
}